### ISSUE TITLE
missing 'searchName' property for item

### ISSUE THREAD

**Issue by Tam2** [isaacHagoel/svelte-dnd-action#427]
I'm getting some weird intermittent errors 
But i can't seem to find anything related to a **searchName** property 

```
action.js:70 Uncaught (in promise) Error: missing 'searchName' property for item {
  "id": 1092346,
  "url": "https://image-url.com/image-1910-wrknyble.jpg",
  "priority": 0
}
    at validateOptions (action.js:70:15)
    at dndzone3 (action.js:28:5)
    at mount (http://localhost:5173/src/routes/(app)/stock/inventory/[id]/_components/pages/_ImagesTab.svelte:1515:48)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=ba16fa64:291:24)
    at mount_component (index.mjs:1949:26)
    at mount (http://localhost:5173/src/routes/(app)/stock/inventory/[id]/+page.svelte:622:4)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=ba16fa64:291:24)
    at mount_component (index.mjs:1949:26)
    at Object.update [as p] (root.svelte? [sm]:50:42)
    at Object.update [as p] (root.svelte? [sm]:45:22)
```

**Comment by isaacHagoel** [comment]
My guess is that you are calling `overrideItemIdKeyNameBeforeInitialisingDndZones("searchName")` somewhere in your code.

**Comment by Tam2** [comment]
I am but on a different page

So i have a page with route /inventory - this is where i'm calling `overrideItemIdKeyNameBeforeInitialisingDndZones('searchName');`

but when i go into /inventory/{id} - I'm not calling it, seems like the issue only happens during client side routing (sveltekit) but if i do a refresh on /inventory/{id} it does a server side load and it works fine

**Comment by isaacHagoel** [comment]
this override is global. it would affect every dndzone that is loaded after it is called.
not sure exactly how the routes affect it but as long as there is no full page refresh it will stick.

**Comment by Tam2** [comment]
Okay that makes sense, i'll simply call `overrideItemIdKeyNameBeforeInitialisingDndZones('id')` within my component to reset it

thank you for your help
